# Generated by Django 4.0.8 on 2022-12-10 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newlifemanagementmember',
            name='title_de',
            field=models.CharField(help_text='Title ( ex: Software Engineer )', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='newlifemanagementmember',
            name='title_en',
            field=models.CharField(help_text='Title ( ex: Software Engineer )', max_length=255, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='newlifemanagementmember',
            name='title_tr',
            field=models.CharField(help_text='Title ( ex: Software Engineer )', max_length=255, null=True, verbose_name='Title'),
        ),
    ]
