# Generated by Django 4.0.8 on 2022-12-10 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0002_newlifemanagementmember_title_de_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlifemanagementmember',
            name='instagram',
            field=models.URLField(blank=True, help_text='Instagram link', verbose_name='Instagram URL'),
        ),
        migrations.AlterField(
            model_name='newlifemanagementmember',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Linkedin link', verbose_name='Linkedin URL'),
        ),
    ]
