# Generated by Django 4.0.8 on 2022-12-10 14:18

from django.db import migrations, models
import life.models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_alter_newlifemanagementmember_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newlifemanagementmember',
            name='image',
            field=models.ImageField(blank=True, upload_to=life.models.management_member_image_path, verbose_name='Member Image'),
        ),
    ]
