# Generated by Django 4.0.8 on 2022-12-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0006_alter_comments_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
