# Generated by Django 4.0.8 on 2022-12-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0007_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Is published', verbose_name='Is Active Comment'),
        ),
    ]
