# Generated by Django 4.0.8 on 2022-12-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0008_comment_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_de',
            field=models.TextField(help_text='ex: Very nice..', null=True, verbose_name='User Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_en',
            field=models.TextField(help_text='ex: Very nice..', null=True, verbose_name='User Comment'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_tr',
            field=models.TextField(help_text='ex: Very nice..', null=True, verbose_name='User Comment'),
        ),
    ]
