# Generated by Django 4.0.8 on 2022-12-10 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0009_comment_comment_de_comment_comment_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'User Comment', 'verbose_name_plural': 'User Comments'},
        ),
        migrations.AlterModelOptions(
            name='newlifemanagementmember',
            options={'ordering': ('position',), 'verbose_name': 'Management Member', 'verbose_name_plural': 'Management Members'},
        ),
    ]
