# Generated by Django 4.0.8 on 2022-12-10 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0012_alter_comment_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='rate',
            field=models.CharField(choices=[('1', '1 Star'), ('2', '2 Star'), ('3', '3 Star'), ('4', '4 Star'), ('5', '5 Star')], help_text='ex: 4', max_length=3, verbose_name='Comment Star'),
        ),
    ]
