# Generated by Django 4.0.8 on 2022-12-19 18:37

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0014_molecule'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('10sinif', '10. Sınıf'), ('11sinif', '11. Sınıf'), ('12sinif', '12. Sınıf'), ('uni', 'Universite')], max_length=27, verbose_name='Classes'),
        ),
    ]
