# Generated by Django 4.0.8 on 2022-12-19 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0015_molecule_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(help_text='What is the ENIAC?', max_length=255, verbose_name='Question Title')),
                ('question_answer', models.CharField(help_text='First Computer', max_length=255, verbose_name='Question Answer')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
    ]
