# Generated by Django 4.0.8 on 2022-12-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0016_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_title', models.CharField(help_text='What is the ENIAC?', max_length=255, verbose_name='Question Title')),
                ('question_title_tr', models.CharField(help_text='What is the ENIAC?', max_length=255, null=True, verbose_name='Question Title')),
                ('question_title_en', models.CharField(help_text='What is the ENIAC?', max_length=255, null=True, verbose_name='Question Title')),
                ('question_title_de', models.CharField(help_text='What is the ENIAC?', max_length=255, null=True, verbose_name='Question Title')),
                ('question_answer', models.CharField(help_text='First Computer', max_length=255, verbose_name='Question Answer')),
                ('question_answer_tr', models.CharField(help_text='First Computer', max_length=255, null=True, verbose_name='Question Answer')),
                ('question_answer_en', models.CharField(help_text='First Computer', max_length=255, null=True, verbose_name='Question Answer')),
                ('question_answer_de', models.CharField(help_text='First Computer', max_length=255, null=True, verbose_name='Question Answer')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
            },
        ),
        migrations.DeleteModel(
            name='Cards',
        ),
    ]
