# Generated by Django 4.0.8 on 2022-12-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0017_card_delete_cards'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='description',
            field=models.TextField(blank=True, verbose_name='Description'),
        ),
    ]
