# Generated by Django 4.0.8 on 2022-12-25 11:16

from django.db import migrations, models
import life.models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0019_molecule_description_de_molecule_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='molecule',
            name='image',
            field=models.ImageField(blank=True, help_text='Molecule Image', null=True, upload_to=life.models.molecule_image_path, verbose_name='Image'),
        ),
    ]
