# Generated by Django 4.0.8 on 2022-12-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0021_molecule_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='molecule',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Slug'),
        ),
    ]
