# Generated by Django 4.0.8 on 2022-12-25 13:04

import ckeditor.fields
from django.db import migrations, models
import life.models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0022_alter_molecule_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Blog Title', max_length=255, verbose_name='Blog Title')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(help_text='Blog Image', upload_to=life.models.blog_image_path, verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
    ]
