# Generated by Django 4.0.8 on 2022-12-25 13:06

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0023_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='description_de',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_tr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_de',
            field=models.CharField(help_text='Blog Title', max_length=255, null=True, verbose_name='Blog Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_en',
            field=models.CharField(help_text='Blog Title', max_length=255, null=True, verbose_name='Blog Title'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(help_text='Blog Title', max_length=255, null=True, verbose_name='Blog Title'),
        ),
    ]
