# Generated by Django 4.0.8 on 2023-01-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0027_favoritemolecule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoleculeTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('image', models.ImageField(upload_to='tests/images/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Test',
                'verbose_name_plural': 'Tests',
            },
        ),
    ]
