# Generated by Django 4.0.8 on 2023-01-29 11:00

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0028_moleculetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleculetest',
            name='classes',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('9sinif', '9. Sınıf'), ('10sinif', '10. Sınıf'), ('11sinif', '11. Sınıf'), ('12sinif', '12. Sınıf'), ('uni', 'Universite')], max_length=34, verbose_name='Classes'),
        ),
    ]
