# Generated by Django 4.0.8 on 2023-01-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0029_moleculetest_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleculetest',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
