# Generated by Django 4.0.8 on 2023-01-29 11:04

from django.db import migrations, models
import life.models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0030_moleculetest_question_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='moleculetest',
            name='test_id',
            field=models.CharField(default=life.models.gen_random_string, max_length=32, unique=True),
        ),
    ]
