# Generated by Django 4.0.8 on 2023-03-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0033_codinggallery_video_alter_moleculetest_test_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codinggallery',
            options={'verbose_name': 'Kodlama Galerisi', 'verbose_name_plural': 'Kodlama Galerisi'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AddField(
            model_name='newlifemanagementmember',
            name='github',
            field=models.URLField(blank=True, help_text='Github link', verbose_name='Github URL'),
        ),
    ]
