# Generated by Django 4.0.8 on 2022-12-10 20:06

from django.db import migrations, models
import newlife.users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to=newlife.users.models.user_profile_image_path, verbose_name='Profile Image'),
        ),
    ]
