# Generated by Django 4.0.8 on 2022-12-25 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_university'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='class_choices',
            field=models.CharField(blank=True, choices=[('9sinif', '9. Sınıf'), ('10sinif', '10. Sınıf'), ('11sinif', '11. Sınıf'), ('12sinif', '12. Sınıf'), ('uni', 'Universite')], max_length=7),
        ),
    ]
